### ISSUE TITLE
Travis master is failing on Xenail due to icub-main/OpenCV

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#511]

**Comment by traversaro** [comment]
First failing build: https://travis-ci.org/robotology/idyntree/builds/473246112 .

**Comment by traversaro** [comment]
The relevant failure is in https://travis-ci.org/robotology/idyntree/jobs/474297464 . 

icub-main (`devel`) compilation is failing on Xenial, I guess after https://github.com/robotology/icub-main/commit/9d9db0234a9dc46f810400dae125a30ff2488f5e :
~~~
Scanning dependencies of target motionCUT
[ 94%] Building CXX object src/modules/motionCUT/CMakeFiles/motionCUT.dir/main.cpp.o
/home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp: In member function 'virtual void ProcessThread::run()':
/home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:282:35: error: invalid initialization of non-const reference of type 'cv::Mat&' from an rvalue of type 'cv::Mat'
                     circle(toCvMat(imgBgrOut),node,1,NODE_ON,2);
                                   ^
In file included from /usr/include/opencv2/opencv.hpp:47:0,
                 from /home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:28:
/usr/include/opencv2/core/core.hpp:2604:19: note:   initializing argument 1 of 'void cv::circle(cv::Mat&, cv::Point, int, const Scalar&, int, int, int)'
 CV_EXPORTS_W void circle(CV_IN_OUT Mat& img, Point center, int radius,
                   ^
/home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:283:35: error: invalid initialization of non-const reference of type 'cv::Mat&' from an rvalue of type 'cv::Mat'
                     circle(toCvMat(imgMonoOpt),node,1,Scalar(255),2);
                                   ^
In file included from /usr/include/opencv2/opencv.hpp:47:0,
                 from /home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:28:
/usr/include/opencv2/core/core.hpp:2604:19: note:   initializing argument 1 of 'void cv::circle(cv::Mat&, cv::Point, int, const Scalar&, int, int, int)'
 CV_EXPORTS_W void circle(CV_IN_OUT Mat& img, Point center, int radius,
                   ^
/home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:296:35: error: invalid initialization of non-const reference of type 'cv::Mat&' from an rvalue of type 'cv::Mat'
                     circle(toCvMat(imgBgrOut),node,1,NODE_OFF,1);
                                   ^
In file included from /usr/include/opencv2/opencv.hpp:47:0,
                 from /home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:28:
/usr/include/opencv2/core/core.hpp:2604:19: note:   initializing argument 1 of 'void cv::circle(cv::Mat&, cv::Point, int, const Scalar&, int, int, int)'
 CV_EXPORTS_W void circle(CV_IN_OUT Mat& img, Point center, int radius,
                   ^
/home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:322:43: error: invalid initialization of non-const reference of type 'cv::Mat&' from an rvalue of type 'cv::Mat'
                             circle(toCvMat(imgBgrOut),node,1,NODE_ON,2);
                                           ^
In file included from /usr/include/opencv2/opencv.hpp:47:0,
                 from /home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:28:
/usr/include/opencv2/core/core.hpp:2604:19: note:   initializing argument 1 of 'void cv::circle(cv::Mat&, cv::Point, int, const Scalar&, int, int, int)'
 CV_EXPORTS_W void circle(CV_IN_OUT Mat& img, Point center, int radius,
                   ^
/home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:323:43: error: invalid initialization of non-const reference of type 'cv::Mat&' from an rvalue of type 'cv::Mat'
                             circle(toCvMat(imgMonoOpt),node,1,Scalar(255),2);
                                           ^
In file included from /usr/include/opencv2/opencv.hpp:47:0,
                 from /home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:28:
/usr/include/opencv2/core/core.hpp:2604:19: note:   initializing argument 1 of 'void cv::circle(cv::Mat&, cv::Point, int, const Scalar&, int, int, int)'
 CV_EXPORTS_W void circle(CV_IN_OUT Mat& img, Point center, int radius,
                   ^
/home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:355:31: error: invalid initialization of non-const reference of type 'cv::Mat&' from an rvalue of type 'cv::Mat'
                 circle(toCvMat(imgBgrOut),centroid,4,Scalar(blueLev,0,redLev),3
                               ^
In file included from /usr/include/opencv2/opencv.hpp:47:0,
                 from /home/travis/build/robotology/idyntree/icub-main/src/modules/motionCUT/main.cpp:28:
/usr/include/opencv2/core/core.hpp:2604:19: note:   initializing argument 1 of 'void cv::circle(cv::Mat&, cv::Point, int, const Scalar&, int, int, int)'
 CV_EXPORTS_W void circle(CV_IN_OUT Mat& img, Point center, int radius,
                   ^
src/modules/motionCUT/CMakeFiles/motionCUT.dir/build.make:62: recipe for target 'src/modules/motionCUT/CMakeFiles/motionCUT.dir/main.cpp.o' failed
make[2]: *** [src/modules/motionCUT/CMakeFiles/motionCUT.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:4226: recipe for target 'src/modules/motionCUT/CMakeFiles/motionCUT.dir/all' failed
make[1]: *** [src/modules/motionCUT/CMakeFiles/motionCUT.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
The command "docker run -it \
  -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
  -v $HOME/.ccache:$HOME/.ccache \
  -w $TRAVIS_BUILD_DIR \
  --env CC \
  --env CXX \
  --env TRAVIS_BUILD_DIR \
  --env TRAVIS_BUILD_TYPE \
  --env TRAVIS_CMAKE_GENERATOR \
  --env VALGRIND_TESTS \
  --env COMPILE_BINDINGS \
  --env FULL_DEPS \
  ubuntu:$UBUNTU \
  sh .ci/install_debian_and_script.sh" exited with 2.
cache.2
store build cache
0.01s1.29snothing changed, not updating cache
Done. Your build exited with 1.

Top
~~~
Given http://wiki.icub.org/wiki/YARP_Supported_Distributions I guess it could make sense that icub-main drops support for Ubuntu 16.04, @pattacini just to confirm: was this intentional? In that case we can just modify iDynTree's Xenial script to not build icub-main .

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/icub-main/commit/f3d359226b245b3ee4803ea87fe69075f0e94ef1 . .
